### PR TITLE
add maxjobsize and maxsubmit limits to job_resources

### PR DESCRIPTION
**Pull request by elhuhdron**
Added two keys to `job_resources` in order to specify maxjobsize and maxsubmit limits. In slurm these correspond to `MaxArraySize` and `MaxSubmitJobs` respectively. The keys are utilized to control the submission loop and deleted so that they are not sent to sbatch directly. Submitted jobs are grouped into groups of maxjobsize and then each submitted as separate jobs. maxsubmit is obeyed by waiting for enough jobs to finish before submitting more jobs.

If the options are not specified, the job submission loop should behave as previously.

### CODE REVIEW

**Comment by philippotto** [comment]
Thank you for your contribution, @elhuhdron! We discussed this issue internally and decided to not merge the PR right now (predominantly because we want to have automated tests for this case, too), but we will target the issue soon. I hope this is alright :v:

**Comment by elhuhdron** [comment]
No problem, that makes sense. My forked version is working fine for me for now. But, yeah, if you guys are able to officially add support for both limits at some point, that would be great. Thanks!

**Comment by daniel-wer** [comment]
@elhuhdron FYI, we have just released a new `cluster_tools` version that honors Slurm's `MaxArraySize` and `MaxSubmitJobs` limits. The limits don't need to be configured in the `job_resources` but are instead determined automatically. For more information, see the [release notes of v1.61](https://github.com/scalableminds/cluster_tools/releases/tag/v1.61).
Let us know if you encounter any issues.

Thanks again for your PR which served as an inspiration for these new features.

**Comment by elhuhdron** [comment]
@daniel-wer, that's great news, thank you! Next time I start a big cuber job I will try it out and report back.

**Pull request closed without merging**
